POST http://localhost:3000/product/bidding/give-up/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibmlja25hbWUiOiJSSU5PIEtBTkciLCJwYXNzd29yZCI6InNoYTUxMjovMW8wQkhrQVM3a0tIdlVnTVEwSSt2R016Ums0THNiQ3U0ZzZSek9PM01zPToyMTE4NDk6NjQ6L1k2eG5PRitnb0ljUW9odjdBbnZhZ0VNNmpjUEp2VGVCbGx4aFZzTzRSVkE5R3JEaE5PU0ZWRUdzRkJhM2VYemd6T3VZSmZLTmFLall3QnVmTEp6L2c9PSIsImlhdCI6MTcwNDgwMDYyOSwiZXhwIjoxNzA0ODA0MjI5fQ.bi9B5U8IeIM7QvDC2PfyivoFoNJ3-zetonbzcNHz5_4

### bidding
POST http://localhost:3000/product/bidding/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibmlja25hbWUiOiJSSU5PIEtBTkciLCJwYXNzd29yZCI6InNoYTUxMjovMW8wQkhrQVM3a0tIdlVnTVEwSSt2R016Ums0THNiQ3U0ZzZSek9PM01zPToyMTE4NDk6NjQ6L1k2eG5PRitnb0ljUW9odjdBbnZhZ0VNNmpjUEp2VGVCbGx4aFZzTzRSVkE5R3JEaE5PU0ZWRUdzRkJhM2VYemd6T3VZSmZLTmFLall3QnVmTEp6L2c9PSIsImlhdCI6MTcwNDgwMDYyOSwiZXhwIjoxNzA0ODA0MjI5fQ.bi9B5U8IeIM7QvDC2PfyivoFoNJ3-zetonbzcNHz5_4

{
    "biddingPrice": 3200
}



### 회원가입 테스트
POST http://localhost:3000/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "email": "rinothehero@gmail.com",
    "nickname": "RINO KANG",
    "password": "310417",
    "departmentId": 49
}

### 로그인 테스트

POST http://localhost:3000/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "rinothehero@gmail.com",
    "password": "310417"
}

### 현재 사용자 정보 테스트

GET http://localhost:3000/users/current-user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcwNDYzMDAyNCwiZXhwIjoxNzA0NjMzNjI0fQ.A2gx-Sg2qONgh6rHGBOZYlvGmbl1mnfUtxDCrqPH7-A
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibmlja25hbWUiOiJSSU5PIEtBTkciLCJwYXNzd29yZCI6InNoYTUxMjovMW8wQkhrQVM3a0tIdlVnTVEwSSt2R016Ums0THNiQ3U0ZzZSek9PM01zPToyMTE4NDk6NjQ6L1k2eG5PRitnb0ljUW9odjdBbnZhZ0VNNmpjUEp2VGVCbGx4aFZzTzRSVkE5R3JEaE5PU0ZWRUdzRkJhM2VYemd6T3VZSmZLTmFLall3QnVmTEp6L2c9PSIsImlhdCI6MTcwNDgwMDYyOSwiZXhwIjoxNzA0ODA0MjI5fQ.bi9B5U8IeIM7QvDC2PfyivoFoNJ3-zetonbzcNHz5_4
