### 회원가입 테스트
POST http://localhost:3000/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "email": "hayeongpark4@naver.com",
    "nickname": "TEST",
    "password": "12345",
    "departmentId": 1
}

### 로그인 테스트

POST http://localhost:3000/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "hayeongpark3@naver.com",
    "password": "12345"
}

### 현재 사용자 정보 테스트

GET http://localhost:3000/users/current-user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcwNDYzMDAyNCwiZXhwIjoxNzA0NjMzNjI0fQ.A2gx-Sg2qONgh6rHGBOZYlvGmbl1mnfUtxDCrqPH7-A
