### 회원가입 테스트
POST http://localhost:3000/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "email": "hayeongpark4@naver.com",
    "nickname": "TEST",
    "password": "12345",
    "departmentId": 1
}

### 로그인 테스트

POST http://localhost:3000/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "password123"
}

# {
#     "email": "hayeongpar@naver.com",
#     "password": "string"
# }

### 현재 사용자 정보 테스트

GET http://localhost:3000/users/current-user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwibmlja25hbWUiOiJ0ZXN0aWUiLCJwYXNzd29yZCI6InNoYTUxMjowZjhOUmYrRWRrVFduS01TYzZzVDBOTnlPK3BKNTFBSkJ4bm9WQW8vSWxJPToyMDI2NTE6NjQ6VVlhVjdBeGt5WWNrNFh1UU0xSEkwdDlFNGlTZDVmMm9GNTk0VmlCM3EwcWdGdFJkaFFVeUdOQWFPZy80RXBBNFhxaERDZmdIYm1NaHVwUk5rMmNFWUE9PSIsImlhdCI6MTcwNDcxNjExNSwiZXhwIjoxNzA0NzE5NzE1fQ.DBGuwM97EM3DkCgeWLveayOXgK6YsvPipDdkFpFFeOc


### 판매 중인 상품 확인

GET http://localhost:3000/users/current-user/product/sell HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywibmlja25hbWUiOiJURVNUIiwicGFzc3dvcmQiOiJzaGE1MTI6WmJBd00waURIZE9tK0J6S0k0a1lXTEVPakJkWHFXL1IrYkxMUlN3UGUwZz06MjA0NjAwOjY0OjNTSUZXa09Hc3NjZXUzRDBXdk9MZDBGZUQwZkh5MkFwTTdGcG9Ub1NpN3ZWSVkwRjh5cktSZG9SU3RVNHdQRXI4U3NhQ1oySkw5ZnFhNWVRbGVvM2hnPT0iLCJpYXQiOjE3MDQ2OTYwNjMsImV4cCI6MTcwNDY5OTY2M30.HcMqr6H1EcJgqSCtjWVp1pA7SmnPWI6N_BTGDEwrFVY

### 상품 상세정보 조회하기

GET http://localhost:3000/products/10 HTTP/1.1
Content-Type: application/json
